### ISSUE TITLE
Support for gnome-shell theme

### ISSUE THREAD

**Issue by radical4ever** [GradienceTeam/Plugins#2]
Hi, i finally found an app for customizing accent colors! thnks for develop it :)!!, the app works great and i wanted to say that its possible to customize the accent color of the gnome-shell. i made a custom theme with that support, the steps i do to change it are the next: i go to `/gnome-shell/gnome-shell-sass/_colors.scss` and i modify the next line:
`$selected_bg_color: (here goes the color on HEX value);` 
and finally i parse the sass located in `/gnome-shell/parse-sass.sh`, reboot  and that's all for changing the default accent color.
i leave the file for the modified theme here:
[default-color.zip](https://github.com/ArtyIF/AdwCustomizer/files/9144856/default-color.zip)
the only thing that is not theme its the "do not disturb switch" that's the only thing i see during my experience. thanks for the app again!

**Comment by 0xMRTT** [comment]
I think that we can integrate this as built-in and not as plugin because it's very useful 

@daudix-UFO ?

**Comment by radical4ever** [comment]
Hi, im on gnome 43 and im trying to theme the shell, but  using the old file makes the ui look horrible, any ideas how to remake the theme and suppoeting it with accent colors?

**Comment by 0xMRTT** [comment]
I'm workking on a plugin for gnome shell

**Comment by radical4ever** [comment]
> I'm workking on a plugin for gnome shell

Awesome!
