### ISSUE TITLE
idea: use this repo as a submodule in the Gradience repo for easy mainteance of plugins

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Plugins#20]
It will make maintenance of plugins way easier

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
RFC: @daudix-UFO, @tfuxu

**Comment by daudix** [comment]
I'm all for!

**Comment by tfuxu** [comment]
Sure, if it would make things easier, we can temporarily set it as a submodule

**Comment by 0xMRTT** [comment]
Done
