### ISSUE TITLE
plugin: Tilix theme

### ISSUE THREAD

**Issue by sidevesh** [GradienceTeam/Plugins#21]
### Plugin description

I see the meson.build mentions some files related to tilix plugin,
is this something already present or in development ?

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
It was present but it seems that tilix follow system theme so it's unnecessary...
