### ISSUE TITLE
Support for KvLibadwaita

### ISSUE THREAD

**Issue by daudix** [GradienceTeam/Plugins#4]
https://github.com/GabePoel/KvLibadwaita

~~It uses colors from [src/colors.json](https://github.com/GabePoel/KvLibadwaita/tree/main/src)~~

This is more "Maybe in future" feature

**Comment by ArtyIF** [comment]
Same as GradienceTeam/Plugins#3 - the format is a lot different, down to the named, so some program rewrites will be needed

**Comment by Akergez** [comment]
i think in KvLibadwaita a lot of colors are hardly given and can not be customized.

**Comment by 0xMRTT** [comment]
dup of #15
